spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/datajpa;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true // \uC774 \uBD80\uBD84\uC740 System.out \uC73C\uB85C \uCD9C\uB825\uB418\uAE30\uC5D0 \uAD8C\uC7A5\uCE58\uC54A\uC74C
        format_sql: true
#        default_batch_fetch_size: 100
#    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
